import tkinter as tk
from tkinter import messagebox
def analyze_and_toggle():
    input_text = text_input.get()
    uppercase_count = sum(1 for char in input_text if char.isupper())
    lowercase_count = sum(1 for char in input_text if char.islower())
    space_count = sum(1 for char in input_text if char.isspace())
    toggled_text = input_text.swapcase()
    result_label.config(text=f"Uppercase: {uppercase_count}, Lowercase: {lowercase_count}, Spaces: {space_count}")
    toggled_output.config(text=f"Toggled Text: {toggled_text}")
root = tk.Tk()
root.title("String Analyzer and Toggle Case")
root.geometry("400x300")
root.config(bg="blue")
text_label = tk.Label(root, text="Enter a string:")
text_label.pack(pady=5)
text_input = tk.Entry(root, width=50)
text_input.pack(pady=5)
analyze_button = tk.Button(root, text="Analyze & Toggle", command=analyze_and_toggle)
analyze_button.pack(pady=10)
result_label = tk.Label(root, text="Uppercase: 0, Lowercase: 0, Spaces: 0")
result_label.pack(pady=5)
toggled_output = tk.Label(root, text="Toggled Text:")
toggled_output.pack(pady=10)
root.mainloop()